### ISSUE TITLE
modify  save() YamlDB .py 

### ISSUE THREAD

**Issue by YanjiangChen** [cloudmesh/yamldb#1]
I think the method which save() in YamlDB.py need add a parameter which decide yaml indent, everyone has different file format requirements

def save(self, filename=None, **kwargs):
        """
        saves the data to the specified filename

        :param filename:
        :type filename:
        :return:
        :rtype:
        """
        name = filename or self.filename
        with open(name, "w") as stream:
            print(kwargs)
            if len(kwargs) > 0:
                from ruamel.yaml import YAML
                yaml = YAML()
                yaml.indent(**kwargs)
                yaml.dump(self.data, stream)
            else:
                import oyaml as yaml
                yaml.dump(self.data, stream, default_flow_style=False)

**Comment by laszewsk** [comment]
That is a good point, I always just use 2 as default. I will try to implement or you can suggest a pull request

We can add it to the save method and if not specified we use 2

Thoughts?

**Comment by laszewsk** [comment]
an indent parameter is added
