### ISSUE TITLE
Removing key from yaml file

### ISSUE THREAD

**Issue by ghost** [cloudmesh/yamldb#2]
I've been looking through the code, and it's not clear how to delete a key from a yaml file.

Can yamlDB do this?

**Comment by laszewsk** [comment]
Example:

db["cloudmesh.test.a"] = "aa"
db.delete("cloudmesh.test")

db["a"] = value
db.delete("a")
del db["a"]

Let me know if this does not work. 

Send an example to this issue and I try implementing it

**Comment by ghost** [comment]
def update_db(key):
    # Updates DB with cached values
    db = YamlDB(filename=cache.get("current_yaml"))
    db.delete("floor." + str(key))

expected behaviour: key and value to be removed from yaml
observed behaviour: key and value are not removed

- key does exist
- yaml does exist

**Comment by laszewsk** [comment]
great. not yet sure when i get to this, but this is a good starting point

**Comment by laszewsk** [comment]
Here some thoughts on this:

- [x] verify the test cases in tests as they include some delete function. I thought they worked.
- [x] elaborate more delete function behaviour
- [ ] create test with 
- [x] implement keys() method
   ```
   db.keys() returns a list of all keys in . format
   db["floor.key"] 

   db.delete["floor"] - remove floor and all its children
   db.delete["floor.key"] -> remove
   db.delete["fool.key.nothing"] -> error 

   del db["floor"]
   del db["floor.key"]
   del ["floor.key.nothing"]
   ```

- [x] make sure this works with python 
   - [x] 3.8
   - [x] 3.9
   - [x] 3.10.8
   - [x] 3.11
- [ ] remove python 3.7 support as discontinued by community

**Comment by voryzen** [comment]
`make sure this works with python 3.8,3.9,3.11`
and python 3.10; I'm using 3.10.8 (if that helps you)

**Comment by laszewsk** [comment]
Yes, would be great if you can help. Either in implementation or test case setup

I have put a template together for testing things in tests/test_delete.py  
If you can do pull requests with adding things you like to see tested that would be the first step.

**Comment by laszewsk** [comment]
i made a first initial test.
It would be great if you add to the test the once that seem not to work so we can develop methods that address them.
the simple delete seems to work. I added another test verifying this in test_delete.py, and added something on the readme. So knowing which cases did not work for you would be greatly helpful to do the next steps

**Comment by ghost** [comment]
I know that this doesn't really belong here, (but I have no idea where to place this, I've not used CloudMesh before)..

when I'm trying to run the tests, this is my output.. (caught when installing CloudMesh)

Collecting cloudmesh
  Downloading cloudmesh-2.3.2.zip (472 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.8/472.8 kB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-oo9hnj0y/cloudmesh_8b1e1281a7fb45739358d43ab2ae782f/setup.py", line 44
          print "Install Test"
          ^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ghost** [comment]
made a yaml file (test.yml) in the test folder:
>floor:
>  key: "value"    #<-- uses two spaces as indent

then changed the test_delete.py file to omit CloudMesh dependencies

> ###############################################################
># pytest -v --capture=no tests/test_delete.py
># pytest -v  tests/test_delete.py
># pytest -v --capture=no  tests/test_delete..py::test_delete::<METHODNAME>
>###############################################################
>
>import os
>from pprint import pprint
>
>import pytest
>from yamldb.YamlDB import YamlDB
>
>filename = "./test.yml"
>filename = os.path.abspath(filename)
>print(filename)
>
>@pytest.mark.incremental
>class TestConfig:
>
>    def test_delete(self):
>        db = YamlDB(filename=filename)
>        db.save()
>        #content = readfile(filename)
>        #print(content)
>        print(db)
>        print(db["floor.key"])  #<-- there was a space here
>        assert db["floor.key"] == "value"
>        assert os.path.isfile(filename)
>        db.delete("floor.key")
>        assert "floor.key" not in db
>        print(db)

that doesn't seem to work either..

raised this error:
E           KeyError: "The key 'floor.key' could not be found in the yaml file '<omitted>/yamldb-main/test.yml'"

venv/lib/python3.10/site-packages/yamldb/YamlDB.py:295: KeyError

**Comment by laszewsk** [comment]
I filed #3 for you

**Comment by laszewsk** [comment]
I added cloudmesh-common to dependencies in requirements-dev.txt

**Comment by laszewsk** [comment]
I updated your suggestion of adding a file based test. SO you can give it a try with

git clone https://github.com/cloudmesh/yamldb.git
cd yamldb
pip install -r requirements.txt
pip install -r requirements-dev.txt
pip install -e .
pytest -v --capture=no tests/test_delete.py

Also be reminded to do a db.save() we die not include it on write, as often people wanted to do multiple changes, instead of just one, so it was better to do the save explicitly

**Comment by ghost** [comment]
I git cloned the latest, so I have all your changes, then I followed your commands, however I'm getting this error.

______________________________________ ERROR collecting tests/test_delete.py _______________________________________
ImportError while importing test module '/home/voryzen/Downloads/yamldb-main/tests/test_delete.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_delete.py:11: in <module>
    from yamldb.YamlDB import YamlDB
E   ModuleNotFoundError: No module named 'yamldb'

**Comment by laszewsk** [comment]
JP can you replicate install of yamldb. It seems I can ot replicate voryzen error that was just reported

**Comment by laszewsk** [comment]
@voryzen what OS do you use?

**Comment by ghost** [comment]
endeavourOS

**Comment by laszewsk** [comment]
@voryzen did you do the cd into yamldb?

**Comment by ghost** [comment]
yes, and I followed the commands, exactly

**Comment by laszewsk** [comment]
hmm this is strange .... its based on arch so it should just behave like regular linux

**Comment by ghost** [comment]
Yea, Endeavour is 'almost' vanilla arch

**Comment by laszewsk** [comment]
i made a change in the commands that includes a cd , have you done the cd ...

**Comment by laszewsk** [comment]
have you also done a venv of python?
I suggest to reinstall python if you can do a new env 
python3 -m venv ~/ENV3
source ~/ENV3
pip install pip -U
pip install cloudmesh-installer
cloudmesh-installer get cmd5
cms help
git clone https://github.com/cloudmesh/yamldb.git
cd yamldb
pip install -r requirements.txt
pip install -r requirements-dev.txt
pip install -e .
pytest -v --capture=no tests/test_delete.py

**Comment by ghost** [comment]
my commands:

git clone https://github.com/cloudmesh/yamldb.git
cd yamldb
python3 -m venv ./venv
source ./venv/bin/activate
pip install -r requirements.txt
pip install -r requirements-dev.txt
pip install -e .
pytest -v --capture=no tests/test_delete.py

I'll try the updated list now... 2 secs

**Comment by ghost** [comment]
doesn't the os_is_windows detect if the OS is windows?
if that's correct, shouldn't test_delete be looking for "/tmp/cloudmesh.yaml"?

===================================================== FAILURES =====================================================
______________________________________________ TestConfig.test_delete ______________________________________________

self = <test_delete.TestConfig object at 0x7f1f06a529b0>

    def test_delete(self):
        HEADING()
        global data
        print (data)
        StopWatch.start("init")
>       db = YamlDB(data=dict(data), filename=filename)

tests/test_delete.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
yamldb/YamlDB.py:48: in __init__
    self.save(filename=filename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <yamldb.YamlDB.YamlDB object at 0x7f1f06f0b160>, filename = '/home/voryzen/.cloudmesh/cloudmesh.yaml'

    def save(self, filename=None):
        """
        saves the data to the specified filename
    
        :param filename:
        :type filename:
        :return:
        :rtype:
        """
        name = filename or self.filename
>       with open(name, "w") as stream:
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/voryzen/.cloudmesh/cloudmesh.yaml'

yamldb/YamlDB.py:143: FileNotFoundError
============================================= short test summary info ==============================================
FAILED tests/test_delete.py::TestConfig::test_delete - FileNotFoundError: [Errno 2] No such file or directory: '/home/voryzen/.cloudmesh/cloudmesh.yaml'


It's 3am here, I should be getting some sleep_

**Comment by jpfleischer** [comment]
@laszewsk 
replicate this behavior by saying
```bash
# this might be a bad idea if you have valuable files in here
rm -rf ~/.cloudmesh

pytest -v --capture=no tests/test_delete.py
```

**Comment by laszewsk** [comment]
@voryzen I updated https://github.com/cloudmesh/yamldb/issues/2#issuecomment-1297418887
i forgot we need to call cms help to create the default dirs needed for the test (unrelated to yamldb realy)

**Comment by ghost** [comment]
What is cms help?

I'll take another look at the errors, later today, and see what I can come up with..

No offense intended, Gregor, you have been immensely helpful, but I'd prefer just to debug yamldb, rather than the test processes.

**Comment by laszewsk** [comment]
1. ok i looked at the delete function and its wrong implemented. I will provide fix soon. A number of developers were task in the summer to fix this, but overlooked the issue apparently.
2. cms help is a commandline tool that creates the directory ~/.cloudmesh you can also create it by other means.
3. cms is a very clever way of managing a component enhanced shell we do not use it much, but it is used in our test for regular yamldb you do not need it.

**Comment by laszewsk** [comment]
first part for delete is to also implement db.keys() that is available now

**Comment by ghost** [comment]
> first part for delete is to also implement db.keys() that is available now

OK, did you want me to try the new code with my project?

**Comment by ghost** [comment]
I tried the code with the update, but to no avail :(

**Comment by ghost** [comment]
if it helps at all, I'm getting this output in the terminal, when running db.delete:

K floor {'one': 'spring', 'two': 'autumn'}
'floor'


does this help? @laszewsk

**Comment by laszewsk** [comment]
A new version of YamlDB was released, with this issue fixed, moving to pyproject.toml, support of python 3.12 
updated docstrings
