### ISSUE TITLE
Error in using yamldb

### ISSUE THREAD

**Issue by AlekseiKondrashov** [cloudmesh/yamldb#6]
Hello! There is an error in using yamldb in my project. `FileNotFoundError: [Errno 2] No such file or directory: ' '`. Although this file exists and all necessary permissions have been granted.

**Comment by AlekseiKondrashov** [comment]
Сode fragment where an error occurs
```
locals = YamlDB(filename='locals.yaml')
data = YamlDB(filename='data.yaml')
bot_lang = data['bot.lang']

```

**Comment by laszewsk** [comment]
use `cms help` before the first use, it creates the dirs

**Comment by AlekseiKondrashov** [comment]
Okay, what's next? The error is still there

> use `cms help` before the first use, it creates the dirs

**Comment by AlekseiKondrashov** [comment]
Exhaust: Traceback (most recent call last):
```
  File "/home/user/Documents/project/main.py", line 13, in <module>
    locals = YamlDB(filename='locals.yaml')
  File "/home/user/yamldb/yamldb/YamlDB.py", line 46, in __init__
    self.load(filename=filename)
  File "/home/user/yamldb/yamldb/YamlDB.py", line 125, in load
    os.makedirs(prefix)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by laszewsk** [comment]
which os?

**Comment by AlekseiKondrashov** [comment]
> which os?

Artix Linux (open rc)

**Comment by laszewsk** [comment]
I created a test for your case and for some reason I can not replicate you issue:

pytest -v --capture=no tests/test_issues.py

However, I noticed that you did not include a value (or it may be included in the yaml file. 
When I add the line 

data['bot.lang'] = "a"

it works. Maybe you can send also the content of locals.yaml and data.yaml or you could check that  the file looks like:

```
bot:
  lang: a
```

Also to test this make sure you use for now the development code as documented in the README.md. This way it is easier to interact with you while doing git pull's on your side for testing

Once we verify it works, I will do a new release

**Comment by laszewsk** [comment]
Ps : I made a fix for if you stand in the same dir where the db is stored

**Comment by AlekseiKondrashov** [comment]
Ok, thank you

**Comment by laszewsk** [comment]
A new version of YamlDB was released, with this issue fixed, moving to pyproject.toml, support of python 3.12 
updated docstrings, fix on recursive key deletion.

**Comment by AlekseiKondrashov** [comment]
Thank you!
